version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sampledb
    ports:
      - "8081:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: